# If you'd like to support anchor.md, you can sponsor the project.
# Uncomment and replace with your own links.
github: [Dhairya0707]
# patreon: # your-patreon
# open_collective: # your-open-collective
# ko_fi: # your-kofi
# buy_me_a_coffee: # your-bmac
